name: Deploy via SFTP
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 SFTP Upload
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          # This maps your current folder to the server folder
          uploads: |
            ./ => public_html/caas/
