name: Deploy via SFTP
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to Hetzner via SFTP
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          SOURCE: "./"
          TARGET: "public_html/caas/"
          ARGS: "-rlgoDzvc -i --delete" # Standard sync settings
